name: Translate via @rmw/deepl-markdown-translate (ESM)

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # 또는 18.x

      # 1) package.json 생성 + npm install
      - name: Prepare & Install
        run: |
          echo '{"type":"module","dependencies":{"@rmw/deepl-markdown-translate":"^0.0.7"}}' > package.json
          npm install

      # 2) Clone 영어 저장소
      - name: Clone English Repository
        env:
          ENGLISH_REPO_PAT: ${{ secrets.ENGLISH_REPO_PAT }}
        run: |
          git clone https://x-access-token:${ENGLISH_REPO_PAT}@github.com/kwan3854/-EN-UnityUIStoryboard-Docs.git english-repo
          cd english-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # 3) 번역 스크립트 실행
      - name: Translate
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: node translate_and_copy.js

      # 4) 커밋 & 푸시
      - name: Push changes
        run: |
          cd english-repo
          git add .
          git commit -m "Translated repository content" || echo "Nothing to commit"
          git push origin main || echo "Nothing to push"