name: Translate Repository (Node.js)

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Korean Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # Node 16 / 18 / LTS 중 하나
          node-version: '16.x'
      
      - name: Install npm dependencies
        run: |
          npm install @rmw/deepl-markdown-translate
          # package.json 자동 생성 (npm init -y) 할 수도 있지만,
          # 어차피 단순 설치만으로 node_modules가 생기면 사용 가능

      - name: Clone English Repository
        env:
          ENGLISH_REPO_PAT: ${{ secrets.ENGLISH_REPO_PAT }}
        run: |
          git clone https://x-access-token:${ENGLISH_REPO_PAT}@github.com/kwan3854/-EN-UnityUIStoryboard-Docs.git english-repo
          cd english-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Translate Markdown using Node script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          node translate_and_copy.js

      - name: Push to English Repository
        run: |
          cd english-repo
          git add .
          git commit -m "Translated repository content" || echo "No changes to commit"
          git push origin main || echo "No changes to push"