name: MD to XLIFF -> DeepL -> MD

on:
  push:
    branches: [main]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create package.json
        run: |
          echo '{"type":"module","dependencies":{}}' > package.json
        
      - name: Install dependencies
        run: |
          npm install @diplodoc/markdown-translation node-fetch form-data
          # node-fetch 최신(v3) 설치 → ESM용
        
      - name: Run ESM Script
        run: |
          node extract_and_deepl.mjs

      - name: Clone English Repo
        env:
          ENGLISH_REPO_PAT: ${{ secrets.ENGLISH_REPO_PAT }}
        run: |
          git clone https://x-access-token:${ENGLISH_REPO_PAT}@github.com/kwan3854/-EN-UnityUIStoryboard-Docs.git english-repo
          cd english-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract & DeepL Compose
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          node extract_and_deepl.js

      - name: Copy to English Repo
        run: |
          cp README.en.md english-repo/
          cd english-repo
          git add .
          git commit -m "Auto-translated README" || echo "No changes"
          git push origin main || echo "No changes"