name: Translate All .md via babeldown

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      ######################################################
      # 1) 원본(KO) 리포 체크아웃
      ######################################################
      - name: Checkout source
        uses: actions/checkout@v3

      ######################################################
      # 2) R 환경 셋업
      ######################################################
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      ######################################################
      # 3) babeldown 설치
      ######################################################
      - name: Install babeldown
        run: |
          Rscript -e 'install.packages("pak", repos="https://cloud.r-project.org")'
          Rscript -e 'pak::pak("ropensci-review-tools/babeldown")'

      ######################################################
      # 4) 영어 리포 클론
      ######################################################
      - name: Clone English Repo
        env:
          ENGLISH_REPO_PAT: ${{ secrets.ENGLISH_REPO_PAT }}
        run: |
          git clone https://x-access-token:${ENGLISH_REPO_PAT}@github.com/kwan3854/-EN-UnityUIStoryboard-Docs.git english-repo
          cd english-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      ######################################################
      # 5) .R 스크립트를 이용해 모든 .md 번역
      ######################################################
      # R 코드에서 list.files()로 .md를 찾아 babeldown::deepl_translate() 호출
      - name: Translate All .md
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          Rscript translate_all.R

      ######################################################
      # 6) 영어 리포에 커밋 & 푸시
      ######################################################
      - name: Commit & Push
        run: |
          cd english-repo
          git add .
          git commit -m "Auto-translated all .md via babeldown" || echo "No changes"
          git push origin main || echo "No changes"