name: Translate Entire Repository

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Korean Repository
        uses: actions/checkout@v3

      - name: List Repository Contents
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Working directory:"
          pwd

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Clone English Repository
        env:
          ENGLISH_REPO_PAT: ${{ secrets.ENGLISH_REPO_PAT }}
        run: |
          echo "Cloning English repository..."
          git clone https://x-access-token:${ENGLISH_REPO_PAT}@github.com/kwan3854/-EN-UnityUIStoryboard-Docs.git english-repo
          cd english-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check Python Script
        run: |
          echo "Checking if translation script exists:"
          ls -la translate_and_copy.py

      - name: Translate and Copy Files
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          echo "Starting translation process..."
          python translate_and_copy.py
          echo "Translation process completed"

      - name: Push to English Repository
        run: |
          cd english-repo
          git add .
          git commit -m "Translated repository content" || echo "No changes to commit"
          git push origin main || echo "No changes to push"